/// Centralized configuration for Rive assets
class RiveAssets {
  RiveAssets._();

  /// Base path for Rive assets
  static const String basePath = 'assets/rive';

  /// Map of client name to list of their Rive files
  static const Map<String, List<String>> clientFiles = {
    // Generated by bin/update_rive_files.dart
  };

  /// Get list of all available clients
  static List<String> get clients => clientFiles.keys.toList();

  /// Get list of Rive files for a specific client
  static List<String> getClientFiles(String clientName) {
    return clientFiles[clientName] ?? [];
  }

  /// Get full asset path for a client's Rive file
  static String getAssetPath(String clientName, String fileName) {
    return '$basePath/$clientName/$fileName';
  }

  /// Check if a file exists for a specific client
  static bool isValidFile(String clientName, String fileName) {
    return clientFiles[clientName]?.contains(fileName) ?? false;
  }
}
